### ISSUE TITLE
How can I setup the database?

### ISSUE THREAD

**Issue by TrungVuDang** [noobpwnftw/chessdb#10]
Hi,

I can get the snapshot here ftp://ftp.chessdb.cn/pub/chessdb/chess-20211203.tar , thank for it

But I couldn't import it to mongodb database, I tried but not success with MongoDB with rocksdb engine https://hub.docker.com/layers/percona-server-mongodb/percona/percona-server-mongodb/3.4/images/sha256-045b5cd70bad776215aa1ddb5cb1bfe275cac109a5de734826ba615c1f7526b8?context=explore

Can you advise what I should do to get it up? 

Thank you

**Comment by noobpwnftw** [comment]
MongoDB is for task queue, not the actual database.

You will need https://github.com/noobpwnftw/ssdb for it, which then it is also necessary that you clone https://github.com/noobpwnftw/terarkdb into `deps/terarkdb` folder(`--recursive`) then compile it, put data in the corresponding places, start the server and access the data.
Now to properly run the scripts that I use, you need to build those PHP modules accordingly, which is used to perform board operations, calculate position keys and so on. You can of course make your own tools to interface with SSDB, it basically communicates in a Redis-alike interface.

**Comment by TrungVuDang** [comment]
Sorry, I tried but did not succeed, I try to build the terarkdb from your repository but fail:
<img width="780" alt="Screen Shot 2022-06-23 at 23 28 51" src="https://user-images.githubusercontent.com/8068759/175356861-5ee19319-a293-4598-88f9-1606f410f086.png">

Then I tried with the terarkdb from bytedance/terarkdb, it built success, then I try to build your ssdb repo, it failed because  it didn't find out the terarkdb library (rocksdb.h & others)

I checked and find out the bytedance/terarkdb changed the destination build folder, to "build" folder, not "output" folder as your library, I copy all from "build" to "output" folder, then try to build your ssdb, but still not work also

Do I miss anything?

**Comment by noobpwnftw** [comment]
It could be that some dependencies are missing but I recommend you examine what the problem is and solve them accordingly.

**Comment by TrungVuDang** [comment]
I surrender, I expect it should be simple as below

```
FROM ubuntu:focal

WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive
ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common \
    build-essential \
    locales \
    make \
    cmake \
    autoconf \
    libaio-dev \
    gcc g++ libfl-dev \
    libtbb-dev \
    zip \
    vim \
    unzip \
    git \
    curl \
    ca-certificates \
    openssl libssl-dev libcurl4-openssl-dev
    
# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/noobpwnftw/ssdb && \
    git clone https://github.com/noobpwnftw/terarkdb ssdb/deps/terarkdb && \
   ./ssdb/build.sh

RUN cd ssdb && make && make install

# Map data & start
```

But it always fail with terark-zip, a plugin of terarkdb, I did try to use different versions of terark-zip, and terarkdb also, but no luck. 

Can you share the source of terarkdb? The source folder with full code of all plugins, no need to download it like https://github.com/noobpwnftw/terarkdb

Thank you

**Comment by noobpwnftw** [comment]
You need to initialize all sub-modules(by git submodule init && git submodule update).
https://github.com/noobpwnftw/terark-zip is my fork of the plugin.

I will try to see what the problem for you when I have time, I'll update here when I have something.

**Comment by noobpwnftw** [comment]
```
FROM quay.io/centos/centos:stream8

WORKDIR /app

ENV TZ=UTC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install dependencies
RUN yum -y install epel-release
RUN yum -y install \
    make \
    cmake \
    autoconf \
    gcc gcc-c++ \
    tbb-devel \
    libaio-devel \
    gperftools-devel \
    git diffutils

# Clear cache
RUN yum clean all

RUN git clone https://github.com/noobpwnftw/ssdb && \
    git clone --recursive https://github.com/noobpwnftw/terarkdb ssdb/deps/terarkdb

RUN cd ssdb && make && make install
```

This works, so probably some tbb linking problem which I will not bother to solve.

**Comment by TrungVuDang** [comment]
Thank you, I can build & run it, but I didn't test it yet, I try to setup this source and there is another issue: 
 Call to undefined function ccegtbprobe() in chessdb/web/chessdb.php on line 1760

Please advise what should I do?

**Comment by noobpwnftw** [comment]
Comment this line :)

**Comment by TrungVuDang** [comment]
Finally, I can make it work with PHP5
<img width="1446" alt="Screen Shot 2022-07-09 at 01 16 43" src="https://user-images.githubusercontent.com/8068759/178048253-f37e785b-24cc-404a-ac4a-3451aa7946d5.png">

Seem the database I used is a little old, can you share a newer version?
Can you share how frequently the database is updated? And how can to update it?

Thank you so much.

**Comment by noobpwnftw** [comment]
Since the database is updated by a number of workers that I run, and it is not trivial to give synchronized differential updates, I usually make a snapshot of current database upon request, and it will not be very frequent due to the sheer size and the nature of ever changing data.

**Comment by TrungVuDang** [comment]
Thanks @noobpwnftw, I will take a look at Stockfish and your workers
