### ISSUE TITLE
Request site feature adjustment

### ISSUE THREAD

**Issue by kenarsene** [noobpwnftw/chessdb#11]
Can you separate the FEN and PGN when copying? instead of having the FEN followed by PGN. Maybe make a new button for PGN only that would be great.

https://www.chessdb.cn/queryc_en/

**Comment by noobpwnftw** [comment]
Do you mean copy FEN without move list? You can click "Set URL" first then on the new page(which will not have move history) and copy FEN there.

**Comment by kenarsene** [comment]
Sorry I meant I want to copy only the move list it's a hassle to delete the fen everytime I copy the movelist. Can you add a button to copy only the pgn/move list without the FEN.

**Comment by noobpwnftw** [comment]
A typical copy currently is something like this:
"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 moves e2e4 c7c5 g1f3 d7d6", the move part("e2e4 c7c5 g1f3 d7d6") is only relevant to the root position so I'm not sure which part should be separated?

**Comment by kenarsene** [comment]
Yes, what I specifically would like is something similar to lichess https://i.imgur.com/TZKEwHD.png

**Comment by noobpwnftw** [comment]
You can now copy history moves directly from the move list section(now it is without the piece icons).
