### ISSUE TITLE
try position best move but nomove found

### ISSUE THREAD

**Issue by AndreaZavatta** [noobpwnftw/chessdb#12]
I try to get the best move from this position: rnbqkbnr/ppppp2p/8/5pp1/4PP2/8/PPPP2PP/RNBQKBNR but no move found
but when I ask to provide follow-up move information for a position this is the response: score:29999,depth:1,pv:d1h5
the best move api doesn't work

**Comment by noobpwnftw** [comment]
It works as intended. There is no guarantee that the database will always return a move.

**Comment by AndreaZavatta** [comment]
Why is it that if I enter this link  I get the best move:
https://www.chessdb.cn/cdb.php?action=querypv&board=rnbqkbnr/ppppp2p/8/5pp1/4PP2/8/PPPP2PP/RNBQKBNR%20w%20KQkq%20-%200%201%20w%20KQkq%20-%200%201

 and if I enter this link it tells me it didn't find the best move?
https://www.chessdb.cn/cdb.php?action=querybest&board=rnbqkbnr/ppppp2p/8/5pp1/4PP2/8/PPPP2PP/RNBQKBNR%20w%20KQkq%20-%200%201

The position is the same, clearly the best move exists and it is d1h5, as the first link reports

**Comment by noobpwnftw** [comment]
Different queries are for different purposes, if you just want raw data, you can use the queryall/pv/score/etc. To suggest a move, the API does a few additional checks to prevent a premature decision.

As for such mate in X positions, it may be possible to improve those checks on trivial stuff, but do you really need the database to suggest such a move?

**Comment by ghost** [comment]
Any idea how good this computer player actually is? I might use it to build a game, but I want an idea first.

Also, why not train the computer player using machine learning, and use that as the basis for the REST api moves? Someone has to have done that.
