### ISSUE TITLE
Why Pikafish can not win this fen?

### ISSUE THREAD

**Issue by leonWerth2702** [noobpwnftw/chessdb#16]
4kac2/3Pa4/4c4/8p/9/9/8P/4C4/3pA4/4KAC2 w

**Comment by leonWerth2702** [comment]
(https://ibb.co/Kw09Ljk)

**Comment by noobpwnftw** [comment]
Why is it my problem?

**Comment by leonWerth2702** [comment]
> Why is it my problem?

This fen can win with engine FreeChess but Pikafish can not solve it. https://ibb.co/DKqMLDk
                                                                                                              https://ibb.co/W536y47

**Comment by noobpwnftw** [comment]
I have nothing to do with any of those engines.
