### ISSUE TITLE
JSON Server Stats

### ISSUE THREAD

**Issue by dav1312** [noobpwnftw/chessdb#17]
Add a `json=1` parameter for https://www.chessdb.cn/statsc.php

Concept response

```json
{
    "status": "ok",
    "positions": 15000000000,
    "queue": {
        "scoring": 100000,
        "sieving": 5000000
    },
    "worker": {
        "backlog": 170000,
        "speed": 400000000
    },
    "egtb": {
        "count": {
            "wdl": 1511,
            "dtz": 1511
        },
        "size": {
            "wdl": 9389829301207,
            "dtz": 9158931859374
        }
    }
}
```

**Comment by noobpwnftw** [comment]
Done.

https://www.chessdb.cn/statsc.php?json=1

**Comment by dav1312** [comment]
> Done.
> 
> [chessdb.cn/statsc.php?json=1](https://www.chessdb.cn/statsc.php?json=1)

Cool! Thanks

**Comment by dav1312** [comment]
The speed is wrong right?
- JSON says 400,000
  `(int)$nps`
- Website says 0.4GNPS (400,000,000)
  `number_format( $nps / 1000000, 3, '.', '' ) . ' GNPS`

Shouldn't the website say Mnps instead of Gnps if divided by 1M? 🤔

**Comment by noobpwnftw** [comment]
Workers report them in Knps, I'll fix json.
