### ISSUE TITLE
DTM棋规问题

### ISSUE THREAD

**Issue by xiangqishare** [noobpwnftw/chessdb#19]
这是其他人发现的问题，他设置了局面进入云库DTM则完全按云库首选出招，结果这让云库和引擎均认为速胜的局面，出现了不变作和。
![Screenshot_20230111_114155_Chrome](https://user-images.githubusercontent.com/100093845/211786211-5c27a960-da21-4f0f-927a-98fe0b804a3d.jpg)
如图所示，红方有四种29978首选，当选择其一后，轮到黑方就会如下图显示
![Screenshot_20230111_114247_Chrome](https://user-images.githubusercontent.com/100093845/211786402-04815b61-4366-4dc3-8fef-0a08468e750c.jpg)
黑方首选将会避开棋规走-29979的着法，而不会走-29978的着法，正常来说，只有黑方会进入违规循环（长将、亚规长捉）才会出现这种情况。但是这里黑方可以一将一捉（n将n捉）来让红方一直保持29978的困顿境地（红方可以炮车一线，再将军来让炮左移，引擎也会这么做但是DTM不会，因为DTM认为这不是最快的）
红方用云库首选，黑方一将一捉和棋示例如下：
9/3k5/9/9/9/4R4/9/3r1C3/4K4/9 w moves f2f6 d2d1 e1e0 d1d6 f6f5 d6d5 f5f6 d5d0 e0e1 d0d6 f6f7 d6d7 f7f3 d7d3 f3f5 d3d1 e1e0 d1d5

**Comment by xiangqishare** [comment]
> 这是其他人发现的问题，他设置了局面进入云库DTM则完全按云库首选出招，结果这让云库和引擎均认为速胜的局面，出现了不变作和。 ![Screenshot_20230111_114155_Chrome](https://user-images.githubusercontent.com/100093845/211786211-5c27a960-da21-4f0f-927a-98fe0b804a3d.jpg) 如图所示，红方有四种29978首选，当选择其一后，轮到黑方就会如下图显示 ![Screenshot_20230111_114247_Chrome](https://user-images.githubusercontent.com/100093845/211786402-04815b61-4366-4dc3-8fef-0a08468e750c.jpg) 黑方首选将会避开棋规走-29979的着法，而不会走-29978的着法，正常来说，只有黑方会进入违规循环（长将、亚规长捉）才会出现这种情况。但是这里黑方可以一将一捉（n将n捉）来让红方一直保持29978的困顿境地（红方可以炮车一线，再将军来让炮左移，引擎也会这么做但是DTM不会，因为DTM认为这不是最快的） 和棋示例如下： 9/3k5/9/9/9/4R4/9/3r1C3/4K4/9 w moves f2f6 d2d1 e1e0 d1d6 f6f5 d6d5 f5f6 d5d0 e0e1 d0d6 f6f7 d6d7 f7f3 d7d3 f3f5 d3d1 e1e0 d1d5

**Comment by noobpwnftw** [comment]
静态查询，使用DTC，否则无法预见规则循环。

**Comment by noobpwnftw** [comment]
自动出步加了一个判断，现在应该不会走最高分的。

**Comment by xiangqishare** [comment]
> 自动出步加了一个判断，现在应该不会走最高分的。

那么这是dtm的问题吗？

**Comment by noobpwnftw** [comment]
其触牙者，即言象形如莱茯根；其触耳者，言象如箕；其触头者，言象如石；其触鼻者，言象如杵；其触脚者，言象如木臼；其触脊者，言象如床；其触腹者，言象如瓮；其触尾者，言象如绳。
