### ISSUE TITLE
云库局面分数bug

### ISSUE THREAD

**Issue by xiangqishare** [noobpwnftw/chessdb#24]
云库一个局面的分数似乎出现了bug
1rbaka3/4nr3/2n1PN3/pcR5p/2p6/9/P1P5P/2c1B4/4C4/2BAKA2R b
这个局面中象3进5被错误记录为-29997，而且负的绝杀奇数不应该出现。
![Screenshot_20231110_234718_Chrome](https://github.com/noobpwnftw/chessdb/assets/100093845/44a8b590-c535-4330-a5be-e71364997c99)

后续会变成-29999。
![Screenshot_20231110_234733_Chrome](https://github.com/noobpwnftw/chessdb/assets/100093845/78a2c5c8-9f29-4013-922b-36a3a7a2d8c8)

**Comment by noobpwnftw** [comment]
删除重算好了

**Comment by xiangqishare** [comment]
> 删除重算好了

再次发现一个类似问题的局面。

2b1kab2/4a4/7c1/p1p5p/9/1rP6/P3P1R1P/2N1r4/C3N4/3AKA3 w moves c2b4 h7h0

**Comment by noobpwnftw** [comment]
删除重算好了
