### ISSUE TITLE
How to request the snapshot Database?

### ISSUE THREAD

**Issue by nghiatruong** [noobpwnftw/chessdb#4]
Hi, Could I have Snapshot Database?

Regards,
Nghia

**Comment by noobpwnftw** [comment]
Sure. Chess, Xiangqi, or both? I will make a snapshot and post links here.

**Comment by nghiatruong** [comment]
Hi, Xiangqi is good enough for me. Thank you so much!

**Comment by noobpwnftw** [comment]
ftp://ftp.chessdb.cn/pub/chessdb/xiangqi-20210701.tar
