### ISSUE TITLE
Rule clarifications

### ISSUE THREAD

**Issue by noobpwnftw** [noobpwnftw/chessdb#7]
From https://github.com/ianfab/Fairy-Stockfish/issues/55#issuecomment-999361655

Current implementation adjudicates all perpetual chases on rooks as lose with well defined exceptions.
Problem arise that AXF rule states that chases by knights and cannons are forbidden(http://www.asianxiangqi.org/English/AXF_rules_Eng.pdf §3.6), in which discovered attacks on rooks from bishops are not clearly defined, while it is somewhat implied from §3.6 that rooks should not be chased by minor pieces and in example 25 the rule book mentions discovered attacks from cannons. Giving perpetual bishop discovered attacks on rooted rooks(advisors cannot formulate such a perpetual) a special case creates other complications such as whether to consider attacks from bishops(and advisors) on rooks in other forms of chases as well, and of course, more work to change code.

Also there is a translation error in the rule book §3.6. I think it is in the best interest of everyone if AXF can have a revised version of the rule book in this regard.

**Comment by xiangqishare** [comment]
旋风、小虫和您的云库，三者其实存在规则分歧，我在几个月前详细测试了一遍。如下
4k4/4a4/4bn3/9/5R3/5C3/9/9/9/4K4 w moves f4e4 e9f9 e4f4 f9e9
1RC1k4/9/4n4/9/9/9/9/4B4/9/4K4 w moves b9b7 e7f9 b7b9 f9e7
这两个局面(实战发现的局面简化) ，云库＝小虫＝和棋。旋风判长捉。
4k4/9/4n4/9/3c5/9/4N4/9/9/3K5 w moves d0e0 e7c8 e0d0 c8e7 d0e0
这个局面(实战发现的局面简化) ，云库＝旋风＝长捉。小虫和棋。
3k5/9/9/9/3nR1p1C/9/9/9/9/4K4 w moves e5e9 d9d8 e9e5 d8d9
云库＝旋风等于和棋。小虫长捉。
9/3kan2C/9/7R1/9/9/9/9/9/4K4 w moves h6h8 f8g6 h8h6 g6f8 h6h8 都判长捉，和上一个局面的区别是上个局面红将军的时候，换了个子捉马。

**Comment by xiangqishare** [comment]
严格讲，引擎规则肯定不算是亚规了，因为亚规图39~41用了矛盾的理由判单方长捉，但引擎都是判双方长捉和棋。
同时，除了士相捉有根车外，亚规也没有说明士相捉有根马炮该如何，比如:5k3/9/9/2r6/9/2n6/3R5/4B4/9/3K5 w moves 
d3d4 c4a3 d4d3 a3c4 虽然引擎都判和，但我才猜测本意是不允许的，和士相捉有根车一样。
亚规确实极度不严谨且不精炼，因为编委会似乎都是国规出身，继承了国规的缺点:将自己比作法律的自负。
