### ISSUE TITLE
能否麻烦您将一些dtm库上传至云库

### ISSUE THREAD

**Issue by xiangqishare** [noobpwnftw/chessdb#8]
您好，我跑了云库以外的一些dtm库，诸如KRPKNNP,KRPKCCP,KRPAAKNNAA,KRPBKNNAA,KRCBBKRAAB,KCCAAKNPB,KCCAAKCPB等等，共16个组合，想麻烦您上传至云库，但找不到联系方式，只找到您的github，所以在此留言，可否?谢谢。

**Comment by noobpwnftw** [comment]
格式不太一样，容量也有限，把需要添加的组合发给我即可。KRPKCCP,KRPKNNP已新增。

**Comment by Alxeusxiao** [comment]
你好，他说的跑完的库都是我自己跑的。128-256G的库已经在百度云上传，链接为http://jump2.bdimg.com/safecheck/index?url=rN3wPs8te/pjz8pBqGzzzz3wi8AXlR5g1NgdDpM6gxJ0rPdNs95lzeHLnFi8JtO+91NVDAWBzdfzcfDa/OoD5cyMDCdtVuN2gs9jjHywypBAvjeLdT+AduhAXahwT/8gS1qfamJn98R4UD0bVTWgY9radjyx/bE5rIXzjSIjtbqoW8dJM27dh3Y9qHh6BM0y，大约能跑玩40个库，重要的有KAARPKAANN，
KBRPKAANN，KAABCPKCP，KAARKANCC，KBBRCKAABR，KNPPKABBC，KNPPKABBN都已经上传，只是限制于百度云的4G原因只能以压缩包形式。

可以加我的QQ：1065208544.

**Comment by Alxeusxiao** [comment]
本人跑库的原因是觉得这些库的理论意义特别大，但是云库没有。我觉得这几个库还是非常精彩的，希望大家都来看一看体会象棋残局的精妙。

如果云库使用，不需要署名，也不需要致谢。

**Comment by xiangqishare** [comment]
> KRPKCCP,KRPKNNP已经新增有限，格式一样一样，容量也需要的组合发给我添加。

和Alexus联系即可，谢谢了

**Comment by xiangqishare** [comment]
> 格式不太一样，容量也有限，把需要添加的组合发给我即可。KRPKCCP,KRPKNNP已新增。
谢谢。
kabrnkabbr
kbnnkbbnp
kbnnkaabnp

**Comment by noobpwnftw** [comment]
@Alxeusxiao 云盘中的列表有个笔误：KBBNKBBBPP应为KBBNKBBPPP

**Comment by Alxeusxiao** [comment]
发现了几个局面（几个库）的棋规问题：
1C7/9/1n1ak4/9/9/9/4P1P2/2p6/9/5K3 b
4k4/4a4/3ab2R1/4r4/3N5/9/9/B3B4/4A4/4K4%20w
2b3bn1/2P1k4/5a3/9/9/9/4n4/9/2RK5/9 w
5a3/4k4/5a3/9/9/7p1/9/5K2B/8N/4c2N1 w(这个局面在我自己跑的库是178步，云库是800步并且有棋规问题)

**Comment by noobpwnftw** [comment]
残局库棋规错误，待修复生成器后全部重跑。
DTM循环步数问题，规则正确后才有意义。

**Comment by xiangqishare** [comment]
> 

云库的规则是否存在问题?比如
4k4/3P5/9/9/3c5/4C4/3c5/9/9/3K5 w moves e4d4 d5e5 d4e4 e5d5 这个是判和棋
9/3kac2C/9/7R1/9/9/9/9/9/5K3 w moves h6h8 f8f6 h8h6 f6f8 h6h8 这个是判长捉
但两者似乎没什么区别，都应该是判同个结果

**Comment by noobpwnftw** [comment]
这两个没问题，一个互相长将和，一个红长捉无根炮

**Comment by xiangqishare** [comment]
> 这两个没问题，一个互相长将和，一个红长捉无根炮

第一个并不是互相长将，黑走的是后炮并不会导致长将。第一个红只是一将一闲，黑是一将兼捉一捉。
第二个也是一将兼捉一捉，判长捉。那么第一个理应也是单方面长捉，却判和棋

**Comment by noobpwnftw** [comment]
第二个黑没有捉子，是红自己送的炮架

**Comment by xiangqishare** [comment]
> 第二个黑没有捉子，是红自己送的炮架

第二个是红一将兼捉 一捉。第一个是黑一将兼捉 一捉，但第一个是判和棋。

**Comment by noobpwnftw** [comment]
我认为第一个判和棋正确，第二个判红犯规正确，两个局面情况有区别。

**Comment by noobpwnftw** [comment]
区别在于，第一个红黑互有主动将军动作（黑捉兵忽略不计），第二个黑方没有主动将或捉的动作，单纯为红长捉炮。

**Comment by xiangqishare** [comment]
> 区别在于，第一个红黑互有主动将军动作（黑捉兵忽略不计），第二个黑方没有主动将或捉的动作，单纯为红长捉炮。

似乎在亚规中并没有依据，第一图红为允许着法。而且，即使第一个局面中的炮六平五改成炮六平四，这样红不存在任何的将或捉。然而还是判和，

**Comment by noobpwnftw** [comment]
第二个与这个有何不同？
9/3kac3/9/7R1/9/9/9/9/9/5K3 w moves h6h8 f8f6 h8h6 f6f8 h6h8

**Comment by xiangqishare** [comment]
> 第二个与这个有何不同？ 9/3kac3/9/7R1/9/9/9/9/9/5K3 w moves h6h8 f8f6 h8h6 f6f8 h6h8

第二个在退车捉炮、同时将军，所以是将兼捉。
和第一个似乎没什么不同(平炮捉兵、同时将军)

**Comment by noobpwnftw** [comment]
第一个局面要么是一将一闲vs一将一闲，要么是一将一闲vs两闲，第二个局面是两捉vs两闲或者一将一捉vs两闲，为什么非要认为是没什么不同的？

**Comment by xiangqishare** [comment]
> 第一个局面要么是一将一闲vs一将一闲，要么是一将一闲vs两闲，第二个局面是两捉vs两闲或者一将一捉vs两闲，为什么非要认为是没什么不同的？

第二个局面，红要么是长捉要么是一将一捉，这是正确的，这里，云库判定为长捉红负。
但是第一个局面，黑要么是长捉要么是一将一闲，红每步都在捉兵。如果帅不在六路(不会被将军)，那么云库就会判定黑长捉，所以很明显，就是将军导致判长捉失效，但是第二个局面却能正确判定长捉。

**Comment by xiangqishare** [comment]
> > 第一个局面要么是一将一闲vs一将一闲，要么是一将一闲vs两闲，第二个局面是两捉vs两闲或者一将一捉vs两闲，为什么非要认为是没什么不同的？
> 
> 第二个局面，红要么是长捉要么是一将一捉，这是正确的，这里，云库判定为长捉红负。 但是第一个局面，也是，黑要么是长捉要么是一将一捉，红每步都在捉兵。如果帅不在六路(不会被将军)，那么云库就会判定黑长捉，所以很明显，就是将军导致判长捉失效，但是第二个局面却能正确判定长捉。

**Comment by xiangqishare** [comment]
> > > 第一个局面要么是一将一闲vs一将一闲，要么是一将一闲vs两闲，第二个局面是两捉vs两闲或者一将一捉vs两闲，为什么非要认为是没什么不同的？
> > 
> > 
> > 第二个局面，红要么是长捉要么是一将一捉，这是正确的，这里，云库判定为长捉红负。 但是第一个局面，也是，黑要么是长捉要么是一将一捉，黑每步都在捉兵。如果帅不在六路(不会被将军)，那么云库就会判定黑长捉，所以很明显，就是将军导致判长捉失效，但是第二个局面却能正确判定长捉。

**Comment by noobpwnftw** [comment]
已调整

**Comment by xiangqishare** [comment]
> 已调整

谢谢，另外，您能否为仙鱼提供象棋规则参考?

**Comment by noobpwnftw** [comment]
这个我也不知道他们为啥不直接撸我代码过去用

**Comment by xiangqishare** [comment]
> 这个我也不知道他们为啥不直接撸我代码过去用

呃。。。好吧。。。那么是是那两个修改的cpp文件吗?

**Comment by noobpwnftw** [comment]
我开源了很多东西，包括刚刚的调整，代码都更新上去了，至于谁要拿去怎么用，那个我就不管了。

**Comment by xiangqishare** [comment]
> 我开源了很多东西，包括刚刚的调整，代码都更新上去了，至于谁要拿去怎么用，那个我就不管了。

好吧，谢谢。
再另外，这两个棋例是不是类似，但是云库的结果也是一个违规一个和棋。3k5/9/9/9/5r3/9/4n4/5C3/4A4/3A1K3 b moves e3d1 f2f1 d1e3 f1f2 e3d1
5k3/9/9/9/9/3c5/3r5/3NB4/4A4/4K4 b moves d4e4 e0d0 e4d4 d0e0

**Comment by xiangqishare** [comment]
> 我开源了很多东西，包括刚刚的调整，代码都更新上去了，至于谁要拿去怎么用，那个我就不管了。

第二个fen，应该用这个更合适
5k3/9/9/2N6/9/1N7/9/4BC3/9/cr1RK4 w moves b4c2 b0c0 c2b4 c0b0
和第一个fen极度相似，都是吃子同时将军

**Comment by xiangqishare** [comment]
> > > 我开源了很多东西，包括刚刚的调整，代码都更新上去了，至于谁要拿去怎么用，那个我就不管了。
> > 
> > 
> > 第一个fen，应该用这个更合适 5k3/9/9/2N6/9/1N7/9/4BC3/9/cr1RK4 w moves b4c2 b0c0 c2b4 c0b0 和第二个fen极度相似，都是抽子，但是结果不同

**Comment by noobpwnftw** [comment]
3k5/9/9/9/5r3/9/4n4/5C3/4A4/3A1K3 b moves e3d1 f2f1 d1e3 f1f2 e3d1
这个两子捉一子，炮始终无根，所以判黑长捉
5k3/9/9/9/9/3c5/3r5/3NB4/4A4/4K4 b moves d4e4 e0d0 e4d4 d0e0
这个在黑方走棋的轮次，马有根，只能算作一捉一闲
5k3/9/9/2N6/9/1N7/9/4BC3/9/cr1RK4 w moves b4c2 b0c0 c2b4 c0b0
这个红马始终是无根的（因为抽将），所以判黑长捉

**Comment by noobpwnftw** [comment]
我理解为，如果A捉B的子无法被立即反杀，则无根，像第三个情况虽然抽将后可以吃炮解将，但这个和车捉马无关，车捉无根马犯规。第二个情况黑方炮牵制士才使马无根，但在黑走棋之前马是有根的，车吃马立即反杀，所以这一轮黑是闲，车炮一起打马的这个轮次马无根（因为可以抽将），所以是一捉一闲。

**Comment by xiangqishare** [comment]
> 我理解为，如果A捉B的子无法被立即反杀，则无根，像第三个情况虽然抽将后可以吃炮解将，但这个和车捉马无关，车捉无根马犯规。第二个情况黑方炮牵制士才使马无根，但在黑走棋之前马是有根的，车吃马立即反杀，所以这一轮黑是闲，车炮一起打马的这个轮次马无根（因为可以抽将），所以是一捉一闲。

我和您的理解应该一致，只不过第二个情况有待商榷。我没能理解黑走棋前有根判闲，一步棋的性质应该是看走棋后造成了什么吧。
第二个情况，黑炮4平5黑之前马有根，所以判闲。那么炮5平4之前黑马也是有根的，为什么就是捉?

**Comment by noobpwnftw** [comment]
第二个情况，黑炮5平4之前马无根啊，士被牵制了。

![screenshot](https://user-images.githubusercontent.com/10750762/164543303-4321c215-3e2d-499b-acc6-3e3fa38d4e79.png)

移动前：车打无根马
移动后：炮打有根马，车打无根马
结果：捉


![screenshot (1)](https://user-images.githubusercontent.com/10750762/164543598-ebdb066a-6183-4fbd-9f16-9ae353c7980b.png)

移动前：炮、车打有根马
移动后：车打无根马
结果：闲

我是这么理解的，假如图2，黑用炮吃马或者车吃马，红能否立即反杀？能，说明马有根。一方又不能连走两步，当然是以走棋前的情况决定有没有根。

**Comment by xiangqishare** [comment]
> 第二个情况，黑炮5平4之前马无根啊，士被牵制了。
> 
> ![screenshot](https://user-images.githubusercontent.com/10750762/164543303-4321c215-3e2d-499b-acc6-3e3fa38d4e79.png)
> 
> 移动前：车打无根马 移动后：炮打有根马，车打无根马 结果：捉
> 
> ![screenshot (1)](https://user-images.githubusercontent.com/10750762/164543598-ebdb066a-6183-4fbd-9f16-9ae353c7980b.png)
> 
> 移动前：炮、车打有根马 移动后：车打无根马 结果：闲
> 
> 我是这么理解的，假如图2，黑用炮吃马或者车吃马，红能否立即反杀？能，说明马有根。一方又不能连走两步，当然是以走棋前的情况决定有没有根。

等下，炮4平5前，马有根不算被捉，炮4平5，马无根被捉，结果为什么是闲

**Comment by noobpwnftw** [comment]
”炮4平5前，马有根不算被捉，炮4平5“，打住，后面发生什么，和马的根无关了，结果闲。

**Comment by xiangqishare** [comment]
> ”炮4平5前，马有根不算被捉，炮4平5“，打住，后面发生什么，和马的根无关了，结果闲。

还是没明白，为什么无关，炮平5断根造成了捉。和第一个fen的马5进4没什么区别。

**Comment by noobpwnftw** [comment]
已调整，全部判犯规

**Comment by xiangqishare** [comment]
> 已调整，全部判犯规

我在仙鱼discord艾特了您，我在这里也发一下
2b2k3/9/9/9/2N2r3/9/2C6/9/9/4K4 w moves c5b7 f5f7 b7c5 f7f5
2b2k3/9/9/9/2N6/9/2C6/9/9/4K4 w moves c5b7 f9f8 b7c5 f8f9
两者都判和棋，出现矛盾

**Comment by noobpwnftw** [comment]
已调整，需要检查是否影响其他判断

**Comment by noobpwnftw** [comment]
残局库棋规测试

- [x] KCPPKANP
- [ ] KABBRNKAABR
- [ ] KRPKABBNN
- [x] KBNNKAACP

**Comment by xiangqishare** [comment]
> 残局库棋规测试
> 
> * [ ]  KCPPKANP
> * [ ]  KABBRNKAABR
> * [ ]  KRPKABBNN
> * [x]  KBNNKAACP

双马相 炮卒双士，dtm步数是不是还是有问题，显示170步，实际上变招最多148步
3k5/4a4/5a3/9/6N2/6B2/5p3/6c2/4K2N1/9 w moves g4i2 f3g3 i2g4 g3f3 g4i2 f3g3 i2g4

**Comment by noobpwnftw** [comment]
> DTM循环步数问题，规则正确后才有意义。

**Comment by xiangqishare** [comment]
> > DTM循环步数问题，规则正确后才有意义。

我看库都传了，还以为修好了

**Comment by noobpwnftw** [comment]
现在需要重新跑以上的库，跑完检查棋规问题，棋规没问题再看别的。跑好的库我会打勾。

**Comment by xiangqishare** [comment]
> 现在需要重新跑以上的库，跑完检查棋规问题，棋规没问题再看别的。跑好的库我会打勾。

对了，为什么dtc不能像dtm那样没有违规循环清零

**Comment by noobpwnftw** [comment]
那不就等于吃子清零的DTM么？

**Comment by xiangqishare** [comment]
> 那不就等于吃子清零的DTM么？

是啊，dtm目标是将死，dtc目标应该是子力变化吧，为什么中象dtc会有违规循环?

**Comment by noobpwnftw** [comment]
犯规也算变化

**Comment by xiangqishare** [comment]
> 犯规也算变化

这又是为何，什么原理
假如犯规不是变化，不是更好吗

**Comment by noobpwnftw** [comment]
DTC的定义就是这样，犯规会改变局面的结果，确实是变化的一种。你想达到的结果实际就是吃子清零的DTM，那么反过来，既然有了DTM，吃子清零会让他更好吗？

**Comment by xiangqishare** [comment]
> DTC的定义就是这样，犯规会改变局面的结果，确实是变化的一种。你想达到的结果实际就是吃子清零的DTM，那么反过来，既然有了DTM，吃子清零会让他更好吗？

因为dtc在守方循环多的情况下，走法太绕。就是体积小的优势。

**Comment by xiangqishare** [comment]
> > DTC的定义就是这样，犯规会改变局面的结果，确实是变化的一种。你想达到的结果实际就是吃子清零的DTM，那么反过来，既然有了DTM，吃子清零会让他更好吗？
> 
> 因为dtc在守方循环多的情况下，走法太绕。就是体积小的优势。

而如果只有子力变化的话，起码比dtm小一些。

**Comment by xiangqishare** [comment]
> DTC的定义就是这样，犯规会改变局面的结果，确实是变化的一种。你想达到的结果实际就是吃子清零的DTM，那么反过来，既然有了DTM，吃子清零会让他更好吗？

还有个问题，为什么国象云库里wdl和dtz体积差不多大?

**Comment by xiangqishare** [comment]
> 已调整，需要检查是否影响其他判断

发现一个棋规问题
3c1k3/9/3R5/9/9/9/3cR4/9/4A4/3K1A3 w moves d0e0 d9e9 e0d0 e9d9
这个按我的理解是红长捉4路炮，云库判为和棋

**Comment by noobpwnftw** [comment]
这个我看判和也没问题

**Comment by xiangqishare** [comment]
> 这个我看判和也没问题

按我的理解
帅平五之前，红六路车不能吃4路炮，帅平五一走就可以了。
帅平六之前，红五路车不能吃4路炮，帅平六一走就可以了。
红长捉

**Comment by noobpwnftw** [comment]
炮有根为何算捉？

**Comment by xiangqishare** [comment]
> 炮有根为何算捉？

六路车和五路车轮流捉炮，4路炮只有炮5平4对五路车算是有根，对六路车不是。

**Comment by noobpwnftw** [comment]
帅六平五之前六路车能吃4路炮？

**Comment by xiangqishare** [comment]
> 平

不能吃4路前炮，所以帅六平五之后就能吃了，这步是捉。
帅五平六之前，五路车不能吃4路炮，但帅五平六之后就能吃了，这步也应该是捉。
两车轮流捉同一个炮

**Comment by noobpwnftw** [comment]
帅六平五之后是能吃，但有根？黑自己搞没了根使得红车又能吃炮，红车也没动，我觉得判和也没什么问题。

**Comment by xiangqishare** [comment]
> 帅六平五之后是能吃，但有根？黑自己搞没了根使得红车又能吃炮，红车也没动，我觉得判和也没什么问题。

帅六平五之前，黑4路前炮确实有根，是针对五路车的，因为六路车根本吃不了炮。帅平五之后，对五路车来说炮仍然有根，但对六路车不算而且它可以吃掉炮。帅平五造成了六路车能吃炮的事实。
并且如果跳出逻辑来看，按照常识，帅平五的目的很可能就是为了能让六路车吃掉炮，

**Comment by noobpwnftw** [comment]
以”帅平五的目的很可能就是为了能让六路车吃掉炮“的角度来看，黑炮平5不改变任何现状，等于送个炮红没吃，我觉得判犯规违反常识。

**Comment by xiangqishare** [comment]
> 以”帅平五的目的很可能就是为了能让六路车吃掉炮“的角度来看，黑炮平5不改变任何现状，等于送个炮红没吃，我觉得判犯规违反常识。

以我对亚规的理解，我方的走子性质应该看走子前后盘面，和对面的应对无关。2b2k3/9/9/9/2N6/2C6/9/9/9/4K4 w moves c5b7 f9f8 b7c5 f8f9 c5b7 
比如这个局面黑方应对不改变被吃子现状，但是红的两步分别造成了马和炮捉象。因为两步走子前，马和炮分别都不能吃象。
根据这个关系，讨论局面的红的两步分别造成了六路车和五路车捉炮。

**Comment by noobpwnftw** [comment]
你说是就是，判断成捉，有没有后遗症再看看

**Comment by noobpwnftw** [comment]
判断根源是帅六平五原先不认为是捉炮，现在判断为捉炮。

这样改需要检查其他情况会不会出问题，最好还是整理一个大表，每次改完什么东西，查一遍各种情况。

**Comment by xiangqishare** [comment]
> 判断根源是帅六平五原先不认为是捉炮，现在判断为捉炮。
> 
> 这样改需要检查其他情况会不会出问题，最好还是整理一个大表，每次改完什么东西，查一遍各种情况。

嗯，我有时间看一下

**Comment by xiangqishare** [comment]
> 判断根源是帅六平五原先不认为是捉炮，现在判断为捉炮。
> 
> 这样改需要检查其他情况会不会出问题，最好还是整理一个大表，每次改完什么东西，查一遍各种情况。

试了一圈没有问题。
不过有个亚规矛盾点，云库应该是设定了被牵制的子不会捉，所以符合了亚规图39~41的判断，不过这样确不符合亚规图105的判断。
您认为亚规图39~41和图105是不是互相矛盾?

**Comment by noobpwnftw** [comment]
严格说起来是，被牵制的子不会捉牵制它的子。
帅六平五之前，车不能吃炮，炮是牵制的一部分，原本判断牵制排除被捉的子，现在不排除。论动机，大家都有动机，大家也都是不动子，你说谁对就谁对。。。亚规是没这条，但是彻底忽略就感觉别扭。

**Comment by xiangqishare** [comment]
> 严格说起来是，被牵制的子不会捉牵制它的子。 帅六平五之前，车不能吃炮，炮是牵制的一部分，原本判断牵制排除被捉的子，现在不排除。论动机，大家都有动机，大家也都是不动子，你说谁对就谁对。。。亚规是没这条，但是彻底忽略就感觉别扭。

我叒发现一个可能的棋规问题3k1a1R1/4aP3/9/9/9/9/9/9/9/5K3 b moves e8d7 h9h7 d7e8 h7h9
这应该也许，是黑长捉吧:-D

**Comment by xiangqishare** [comment]
> > 严格说起来是，被牵制的子不会捉牵制它的子。 帅六平五之前，车不能吃炮，炮是牵制的一部分，原本判断牵制排除被捉的子，现在不排除。论动机，大家都有动机，大家也都是不动子，你说谁对就谁对。。。亚规是没这条，但是彻底忽略就感觉别扭。
> 
> 我叒发现一个可能的棋规问题3k1a1R1/4aP3/9/9/9/9/9/9/9/5K3 b moves e8d7 h9h7 d7e8 h7h9 这应该也许，是黑长捉吧:-D

**Comment by xiangqishare** [comment]
> 严格说起来是，被牵制的子不会捉牵制它的子。 帅六平五之前，车不能吃炮，炮是牵制的一部分，原本判断牵制排除被捉的子，现在不排除。论动机，大家都有动机，大家也都是不动子，你说谁对就谁对。。。亚规是没这条，但是彻底忽略就感觉别扭。

😳不好意思可能又要制造麻烦了，这个局面1CRck4/9/3a5/9/9/9/9/9/3CA4/5K3 w moves e1d2 d7e8 d2e1 e8d7
红方两步走子前 车吃黑炮会被反吃。走子后则可以吃掉黑炮不被反吃。云库却判和

**Comment by noobpwnftw** [comment]
没发现问题

**Comment by xiangqishare** [comment]
> 没发现问题

搞反了，应该是这样。1CRck4/9/3a5/9/9/9/9/9/3CA4/5K3 b moves d7e8 e1d2 e8d7 d2e1

**Comment by noobpwnftw** [comment]
也没发现问题

**Comment by xiangqishare** [comment]
> 也没发现问题

红方走士之前，红车吃炮都会被黑将反吃。
走士之后，红车就可以白吃炮。

**Comment by noobpwnftw** [comment]
修好了

**Comment by xiangqishare** [comment]
> 修好了

发现一个循环局面，简化后为
9/2N1k4/9/2r6/2b6/3C5/9/4B4/9/5K3 w moves d4c4 c5e7 c8a7 c6a6 c4d4 e7c5 a7c8 a6c6
云库判为和棋。
是否是象5进3的问题?

**Comment by Alxeusxiao** [comment]
最长局面的统计方法是不是有问题？
统计方法是红胜最长局面是红线，黑胜最长局面是黑先，但应该最长局面是不管红先黑先的.....
