### ISSUE TITLE
残局库统计中一个微小的问题

### ISSUE THREAD

**Issue by xiangqishare** [noobpwnftw/chessdb#9]
![Screenshot_20220611_110513_com android chrome](https://user-images.githubusercontent.com/100093845/173181447-6f673cc4-3376-4336-8ada-4288bb7c9483.png)
![Screenshot_20220611_110453_com android chrome](https://user-images.githubusercontent.com/100093845/173181464-06702011-e05d-46cb-87b4-3c08e6950df9.png)
如图所示，残局库统计中胜率为100%，实际上不应该是100%

**Comment by noobpwnftw** [comment]
已处理

**Comment by xiangqishare** [comment]
> 已处理

我想问一下，国象的noob 3回合、8回合 v3之类的开局书，是怎么做的

**Comment by noobpwnftw** [comment]
https://github.com/noobpwnftw/chessdb/blob/master/scripts/dumperc.php

**Comment by xiangqishare** [comment]
> https://github.com/noobpwnftw/chessdb/blob/master/scripts/dumperc.php

开局书是否没有黑优的开局

**Comment by noobpwnftw** [comment]
跑出来什么就是什么 谁优看造化

**Comment by xiangqishare** [comment]
> 跑出来什么就是什么 谁优看造化

我的意思是，似乎国象开局书基本都是白优，这有什么用意吗？

**Comment by noobpwnftw** [comment]
没有用意，只反映客观事实

**Comment by xiangqishare** [comment]
> 没有用意，只反映客观事实

懂了谢谢

**Comment by xiangqishare** [comment]
> 没有用意，只反映客观事实

软件圈内流传的“旋风测试百万fen”是大佬你生成的吗？这算是私人的还是大众分享的?
